# Generated by Django 2.1 on 2018-09-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contetn',
            new_name='content',
        ),
    ]
